version: '3.1'

services:
  mongo:
    container_name: mongo_dev
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: rickandmorty
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network

  backend:
    container_name: backend_dev
    build: ./backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/rickandmorty
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    container_name: frontend_dev
    build: ./frontend
    ports:
      - 4200:4200
    environment:
      API_URL: http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
volumes:
  mongodb_data_container: